language: python

addons:
        postgresql: "9.3"

python:
        - "2.7"
install:
        - pip install -r requirements.txt
before_script:
        - psql -U postgres -d postgres -f dbscripts/init-template.sql
        - dbscripts/init.sh
        - python LakeGIS/manage.py syncdb --noinput
script:
        - python LakeGIS/manage.py test lakegis_app
