DROP DATABASE IF EXISTS lakegis;
DROP USER IF EXISTS lakegis;
CREATE USER lakegis WITH PASSWORD NULL;
CREATE DATABASE lakegis WITH TEMPLATE = template0 ENCODING = 'UTF-8';
GRANT ALL ON DATABASE lakegis TO lakegis;
\c lakegis
CREATE EXTENSION postgis;
